definitions:
  common.Config:
    type: object
  middlewares.Response:
    properties:
      code:
        type: integer
      data: {}
      message:
        type: string
    type: object
  request.Body:
    properties:
      data:
        type: string
      id:
        maximum: 64
        type: integer
    required:
    - id
    type: object
  request.Invoke:
    properties:
      method:
        type: string
      path:
        type: string
    type: object
  request.Login:
    properties:
      user_name:
        type: string
      user_password:
        type: string
    required:
    - user_name
    - user_password
    type: object
  request.Question:
    type: object
  request.Submit:
    properties:
      code:
        description: '"用户代码"'
        maxLength: 1024
        type: string
      language:
        description: '"编程语言"'
        maxLength: 64
        type: string
      question_id:
        description: '"判题id"'
        maximum: 64
        type: integer
    required:
    - code
    - language
    - question_id
    type: object
  request.UpdateQuestion:
    properties:
      accept_num:
        description: '"题目通过数"'
        type: integer
      answer:
        description: '"题目答案,数组"'
        items:
          type: string
        maxItems: 512
        type: array
      content:
        description: '"内容"'
        maxLength: 1024
        type: string
      id:
        maximum: 64
        type: integer
      judge_case:
        description: '"判题用例json数组,输入用例"'
        items:
          type: string
        maxItems: 1024
        type: array
      judge_config:
        description: '"判题配置json对象,内存限制，时间限制"'
        items:
          $ref: '#/definitions/common.Config'
        maxItems: 64
        type: array
      submit_num:
        description: '"题目提交数'
        type: integer
      tag:
        description: '"标签列表json数组"'
        items:
          type: string
        maxItems: 128
        type: array
      title:
        description: '"标题"'
        maxLength: 512
        type: string
      user_id:
        description: '"创建用户id"'
        maximum: 64
        type: integer
    required:
    - id
    - user_id
    type: object
  request.UpdateUser:
    properties:
      data:
        $ref: '#/definitions/request.Body'
      type:
        enum:
        - password
        - avatar
        type: string
    type: object
  request.User:
    properties:
      avatar_url:
        type: string
      user_name:
        maxLength: 64
        type: string
      user_password:
        maxLength: 128
        type: string
    required:
    - user_name
    - user_password
    type: object
info:
  contact: {}
paths:
  /admin/create_question:
    post:
      consumes:
      - application/json
      description: Create question
      parameters:
      - description: create question
        in: body
        name: createRequest
        required: true
        schema:
          $ref: '#/definitions/request.Question'
      produces:
      - application/json
      responses:
        "200":
          description: ok
          schema:
            $ref: '#/definitions/middlewares.Response'
        "400":
          description: bad request
          schema:
            $ref: '#/definitions/middlewares.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/middlewares.Response'
      summary: Create question
      tags:
      - question
  /admin/delete_question:
    get:
      consumes:
      - application/json
      description: Delete question
      parameters:
      - description: delete question
        in: query
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: ok
          schema:
            $ref: '#/definitions/middlewares.Response'
        "400":
          description: bad request
          schema:
            $ref: '#/definitions/middlewares.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/middlewares.Response'
      summary: Delete question
      tags:
      - question
  /admin/delete_submit:
    get:
      consumes:
      - application/json
      description: Delete submit
      parameters:
      - description: delete submit
        in: query
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: ok
          schema:
            $ref: '#/definitions/middlewares.Response'
        "400":
          description: bad request
          schema:
            $ref: '#/definitions/middlewares.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/middlewares.Response'
      summary: Delete submit
      tags:
      - submit
  /admin/delete_user:
    get:
      consumes:
      - application/json
      description: User registration
      parameters:
      - description: delete user by id
        in: query
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: ok
          schema:
            $ref: '#/definitions/middlewares.Response'
        "400":
          description: bad request
          schema:
            $ref: '#/definitions/middlewares.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/middlewares.Response'
      summary: User registration
      tags:
      - user
  /admin/get_users:
    get:
      consumes:
      - application/json
      description: Get user list
      parameters:
      - description: get user list by id
        in: query
        name: id
        required: true
        type: string
      - description: get user list by name
        in: query
        name: name
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: ok
          schema:
            $ref: '#/definitions/middlewares.Response'
        "400":
          description: bad request
          schema:
            $ref: '#/definitions/middlewares.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/middlewares.Response'
      summary: Get user list
      tags:
      - user
  /admin/invoke/count:
    post:
      consumes:
      - application/json
      description: get api invoke count
      parameters:
      - description: invoke request
        in: body
        name: invokeRequest
        required: true
        schema:
          $ref: '#/definitions/request.Invoke'
      produces:
      - application/json
      responses:
        "200":
          description: ok
          schema:
            $ref: '#/definitions/middlewares.Response'
        "400":
          description: bad request
          schema:
            $ref: '#/definitions/middlewares.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/middlewares.Response'
      summary: get api invoke count
      tags:
      - invoke
  /admin/update_question:
    post:
      consumes:
      - application/json
      description: Update question
      parameters:
      - description: update question
        in: body
        name: updateRequest
        required: true
        schema:
          $ref: '#/definitions/request.UpdateQuestion'
      produces:
      - application/json
      responses:
        "200":
          description: ok
          schema:
            $ref: '#/definitions/middlewares.Response'
        "400":
          description: bad request
          schema:
            $ref: '#/definitions/middlewares.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/middlewares.Response'
      summary: Update question
      tags:
      - question
  /admin/update_user:
    post:
      consumes:
      - application/json
      description: Update user
      parameters:
      - description: update user
        in: body
        name: updateRequest
        required: true
        schema:
          $ref: '#/definitions/request.UpdateUser'
      produces:
      - application/json
      responses:
        "200":
          description: ok
          schema:
            $ref: '#/definitions/middlewares.Response'
        "400":
          description: bad request
          schema:
            $ref: '#/definitions/middlewares.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/middlewares.Response'
      summary: Update user
      tags:
      - user
  /question/get_questions:
    get:
      consumes:
      - application/json
      description: get question list
      parameters:
      - description: page number
        in: query
        name: page
        required: true
        type: string
      - description: page size
        in: query
        name: pageSize
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: ok
          schema:
            $ref: '#/definitions/middlewares.Response'
        "400":
          description: bad request
          schema:
            $ref: '#/definitions/middlewares.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/middlewares.Response'
      summary: get question list
      tags:
      - question
  /question/search_questions:
    get:
      consumes:
      - application/json
      description: Search question
      parameters:
      - description: search question
        in: query
        name: keyword
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: ok
          schema:
            $ref: '#/definitions/middlewares.Response'
        "400":
          description: bad request
          schema:
            $ref: '#/definitions/middlewares.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/middlewares.Response'
      summary: Search question
      tags:
      - question
  /submit/create_submit:
    post:
      consumes:
      - application/json
      description: Create submit
      parameters:
      - description: create submit
        in: body
        name: createRequest
        required: true
        schema:
          $ref: '#/definitions/request.Submit'
      produces:
      - application/json
      responses:
        "200":
          description: ok
          schema:
            $ref: '#/definitions/middlewares.Response'
        "400":
          description: bad request
          schema:
            $ref: '#/definitions/middlewares.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/middlewares.Response'
      summary: Create submit
      tags:
      - submit
  /submit/get_submits:
    get:
      consumes:
      - application/json
      description: get submit list
      parameters:
      - description: page number
        in: query
        name: page
        required: true
        type: string
      - description: page size
        in: query
        name: pageSize
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: ok
          schema:
            $ref: '#/definitions/middlewares.Response'
        "400":
          description: bad request
          schema:
            $ref: '#/definitions/middlewares.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/middlewares.Response'
      summary: get submit list
      tags:
      - submit
  /submit/search_submits:
    get:
      consumes:
      - application/json
      description: Search submit
      parameters:
      - description: search submit
        in: query
        name: keyword
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: ok
          schema:
            $ref: '#/definitions/middlewares.Response'
        "400":
          description: bad request
          schema:
            $ref: '#/definitions/middlewares.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/middlewares.Response'
      summary: Search submit
      tags:
      - submit
  /user/login:
    post:
      consumes:
      - application/json
      description: User login
      parameters:
      - description: user login
        in: body
        name: loginRequest
        required: true
        schema:
          $ref: '#/definitions/request.Login'
      produces:
      - application/json
      responses:
        "200":
          description: ok
          schema:
            $ref: '#/definitions/middlewares.Response'
        "400":
          description: bad request
          schema:
            $ref: '#/definitions/middlewares.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/middlewares.Response'
      summary: User login
      tags:
      - user
  /user/register:
    post:
      consumes:
      - application/json
      description: User registration
      parameters:
      - description: create user
        in: body
        name: createRequest
        required: true
        schema:
          $ref: '#/definitions/request.User'
      produces:
      - application/json
      responses:
        "200":
          description: ok
          schema:
            $ref: '#/definitions/middlewares.Response'
        "400":
          description: bad request
          schema:
            $ref: '#/definitions/middlewares.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/middlewares.Response'
      summary: User registration
      tags:
      - user
swagger: "2.0"
