Elasticsearch:
  addresses: [ "http://127.0.0.1:9200" ]
  username: ""
  password: ""
Database:
  username: root
  password: root
  host: 127.0.0.1
  port: 3306
  db_name: oj
  max_idle_conns: 10
  max_open_conns: 100
  conn_max_lifetime: 3600
Redis:
  host: 127.0.0.1
  port: 6379
  password: ""
  db: 0
RabbitMQ:
  username: "xissg"
  password: "0709"
  host: "localhost"
  port: 5672
  publish_type: "publish"
  exchange_name: "judge_exchange"
  routing_key: "judge"
  queue_name: "judge_queue"
  consumer_tag: "judge_consumer"
Server:
  host: 127.0.0.1
  port: 8082
Image:
  javascript: "node:22-alpine"
  python: "python:3.12-alpine"
  java: "java:6"
  go: "golang:latest"
  cpp: "eclipse/cpp_gcc:latest"
  c: "gcc:13.3.0"
AI:
  #host_url: "wss://spark-api.xf-yun.com/v1.1/chat"
  host_url: "wss://spark-api.xf-yun.com/v3.5/chat"
  app_id: "3fd9659c"
  api_secret: "NDM4MjZjY2VkYzE0MzE5NWJlMGEyOTc1"
  api_key: "030ebc99d5951548bf7991edd9d83a2c"
  flexibility: 4 #灵活性1-6
  randomness: 0.8 #随机性0-1
Log: #输出路径的文件需提前创建
  output_paths: [ "stdout","public/log/stdout.log" ]
  error_output_paths: [ "public/log/error.log" ]
Jwt:
  secret: "secret_key"
  expiration: 3600 #时间单位是秒